# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9576dc7fbaa41ddf6931dc527747fdba056d7436504af18c9af2ce6fd980baa678395fe106bd9e15b34c1fc0233c83c6b8c9203430cc96b85c03b8d3c71fd40e

test:
  secret_key_base: daa002b9884c61cf65d1f812a882bff6753247cd7757d2887bf194c66b015fffe6aee47d2de99f82c090d9a1069cbfd6b92344be05dc1d762639250780fc4de0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
